[package]
name = "TokyoFix"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
bytes = "1.9.0"
chrono = "0.4.39"
config = { version = "0.14.0", features = ['toml'] }
glob = "0.3.2"
